# Generated by Django 2.2.2 on 2019-10-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='collage_name',
        ),
    ]
